site_name: DockSTARTer
site_url: https://dockstarter.com
site_author: GhostWriters
site_description: DockSTARTer helps you get started with home server apps running in Docker.

repo_name: GhostWriters/DockSTARTer
repo_url: https://github.com/GhostWriters/DockSTARTer

copyright: Copyright &copy; 2023 GhostWriters

theme:
  name: modern
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon:  material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/icon.png

extra:
  analytics:
    provider: google
    property: G-QVNLHE95FS
  social:
    - icon: fontawesome/brands/discord
      link: https://dockstarter.com/discord
    - icon: fontawesome/brands/github
      link: https://github.com/GhostWriters/DockSTARTer
  status:
    deprecated: This application is deprecated. Use at your own risk.

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - awesome-nav
  - search
